<?php
/**
 * Generated by the WordPress Meta Box Generator
 * https://jeremyhixon.com/tool/wordpress-meta-box-generator/
 * 
 * Retrieving the values:
 * Title = get_post_meta( get_the_ID(), 'cffapt_title', true )
 * Link = get_post_meta( get_the_ID(), 'cffapt_link', true )
 */
class CFFAPT_Link_List {
	private $config = '{"title":"Link List Repeater","prefix":"cffapt_","domain":"cffapt","class_name":"CFFAPT_Link_List","post-type":["page"],"context":"normal","priority":"default","fields":[{"type":"text","label":"Title","id":"cffapt_title"},{"type":"url","label":"Link","id":"cffapt_link"}]}';

	public function __construct() {
		$this->config = json_decode( $this->config, true );
		add_action( 'add_meta_boxes', [ $this, 'add_meta_boxes' ] );
		add_action( 'save_post', [ $this, 'save_post' ] );
	}

	public function add_meta_boxes() {

        $cffapt_settings_options = get_option( 'cffapt_options' );
        $cffapt_post_types = $cffapt_settings_options['cffapt_post_types'];

        if( $cffapt_post_types ) {
            foreach( $cffapt_post_types as $post_type ) {
                add_meta_box(
                    sanitize_title( $this->config['title'] ),
                    $this->config['title'],
                    [ $this, 'add_meta_box_callback' ],
                    $post_type,
                    $this->config['context'],
                    $this->config['priority']
                );
            }
        }
	}

	public function save_post( $post_id ) {

        if ( isset( $_POST['list_link'] ) ) {
            update_post_meta( $post_id, 'cffapt_list_link', $_POST['list_link'] );
        }
		
	}

	public function add_meta_box_callback() {
		$this->fields_table();
	}

	private function fields_table() {
        global $post;
	?>
        <div class="repeater repeaterWrap">
            <div data-repeater-list="list_link">
                <?php 
                    if ( metadata_exists( 'post', $post->ID, 'cffapt_list_link' ) ): 
                        $cffapt_list_links = get_post_meta( $post->ID, 'cffapt_list_link', true );
                        if( $cffapt_list_links ): 
                            $i=1;
                            foreach( $cffapt_list_links as $cffapt_list_link ):
                ?>  
                    <div data-repeater-item class="repeaterItemWrap">

                        <div class="fieldsWrap">
                            <div class="field">
                                <label for="cffapt_title_<?php echo $i; ?>">Title</label>
                                <div class="contorl">
                                    <input class="regular-text" id="cffapt_title_<?php echo $i; ?>" name="cffapt_title" type="text" value="<?php echo $cffapt_list_link['cffapt_title']; ?>">
                                </div>
                            </div>

                            <div class="field">
                                <label for="cffapt_link_<?php echo $i; ?>">Link</label>
                                <div class="contorl">
                                    <input class="regular-text" id="cffapt_link_<?php echo $i; ?>" name="cffapt_link" type="url" value="<?php echo $cffapt_list_link['cffapt_link']; ?>">
                                </div>
                            </div>
                        </div>

                        <input data-repeater-delete type="button" value="Delete" class="delete"/>
                    </div>
                    <?php $i++; endforeach; endif; ?>
                <?php else: ?>
                    <div data-repeater-item class="repeaterItemWrap">
                        <div class="fieldsWrap">
                            <?php foreach ( $this->config['fields'] as $field ): ?>
                                <div class="field">
                                    <?php $this->label( $field ); ?>
                                    <div class="contorl"><?php $this->field( $field ); ?></div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                        <input data-repeater-delete type="button" value="Delete" class="delete" />
                    </div>
                <?php endif; ?>
            </div>
            <input data-repeater-create type="button" value="Add" class="add"/>
            <div class="clear"></div>
        </div>
        <?php
	}

	private function label( $field ) {
		switch ( $field['type'] ) {
			default:
				printf(
					'<label class="" for="%s">%s</label>',
					$field['id'], $field['label']
				);
		}
	}

	private function field( $field ) {
		switch ( $field['type'] ) {
			default:
				$this->input( $field );
		}
	}

	private function input( $field ) {
		printf(
			'<input class="regular-text %s" id="%s" name="%s" %s type="%s" value="%s">',
			isset( $field['class'] ) ? $field['class'] : '',
			$field['id'], $field['id'],
			isset( $field['pattern'] ) ? "pattern='{$field['pattern']}'" : '',
			$field['type'],
			$this->value( $field )
		);
	}

	private function value( $field ) {
		global $post;
		if ( metadata_exists( 'post', $post->ID, $field['id'] ) ) {
			$value = get_post_meta( $post->ID, $field['id'], true );
		} else if ( isset( $field['default'] ) ) {
			$value = $field['default'];
		} else {
			return '';
		}
		return str_replace( '\u0027', "'", $value );
	}

}
new CFFAPT_Link_List;